name: week-5
dependencies:
  - python=3.11
  - pip
  - pip:
    - ipykernel  # for Jupyter Notebook
    - plotly
    - nbformat
    - streamlit
    - seaborn
    - pandas
    - numpy
    - matplotlib
